 - name: install mysql libraries
   ansible.builtin.pip:
         name: " {{item}} "
         executable: pip3.9
   loop:
         - cryptography
         - PyMySQL   
         - boto3
         - botocore  
         
 - name: install mysql
   ansible.builtin.package:
         name: mysql-server
         state: installed     
 - name : enable mysql
   ansible.builtin.service:
          name: mysqld
          state: started
          enabled: yes
 - name: connect to mysqlserver
   community.mysql.mysql_info:
           login_user: "{{ mysql_user }}"
           login_password: "{{ lookup('amazon.aws.aws_ssm', '/expense/mysql/mysql_root_password', decrypt=False ) }}"
           login_host: "{{ mysql_host }}"
   register: mysql_info
   ignore_errors: true
 - name: print output
   ansible.builtin.debug:
       msg: "mysql information :{{mysql_info}}"   
 - name:  setting root password
   ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ lookup('amazon.aws.aws_ssm', '/expense/mysql/mysql_root_password', decrypt=False )}} "
   when: mysql_info.failed is true