 - name: install mysql libraries
   ansible.builtin.pip:
         name: " {{item}} "
         executable: pip3.9
   loop:
         - cryptography
         - PyMySQL     
         
 - name: install mysql
   ansible.builtin.package:
         name: mysql-server
         state: installed     
 - name : enable mysql
   ansible.builtin.service:
          name: mysqld
          state: started
          enabled: yes
 - name: connect to mysqlserver
   ommunity.mysql.mysql_info:
           login_user: root
           login_password: "{{mysql_root_password}}"
           login_host: mysql.kittudevops.shop 
   register: mysql_info
   ignore_errors: true
 - name: print output
   ansible.builtin.debug:
       msg: "mysql information :{{mysql_info}}"   
 - name:  setting root password
   ansible.builtin.command: "mysql_secure_installation --set-root-pass {{mysql_root_password}} "
     when: mysql_info.failed is true