- name: delete app directory
  tags:
  - deployment
  ansible.builtin.file:
     name: "{{app_loc}}"
     state: absent
- name: create app directory
  tags:
  - deployment
  ansible.builtin.file:
     name: "{{app_loc}}"
     state: directory
- name: downloade ans unzip application code
  tags:
  - deployment
  ansible.builtin.unarchive:
     src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{component}}-v2.zip
     dest: "{{app_loc}}"
     remote_src: yes